services:
  # FastAPI Backend
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-test_key}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: ["python", "main.py", "api", "--host", "0.0.0.0", "--port", "8000"]

  # Streamlit UI
  ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - UI_API_BASE_URL=http://api:8000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      - api
    command: ["python", "main.py", "ui", "--port", "8501"]